/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SubjekIndexRouteImport } from './routes/subjek.index'
import { Route as SubjekSubjectIndexRouteImport } from './routes/subjek.$subject.index'
import { Route as SubjekSubjectYearRouteImport } from './routes/subjek.$subject.$year'
import { Route as KuizSubjectYearTopicRouteImport } from './routes/kuiz.$subject.$year.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjekIndexRoute = SubjekIndexRouteImport.update({
  id: '/subjek/',
  path: '/subjek/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjekSubjectIndexRoute = SubjekSubjectIndexRouteImport.update({
  id: '/subjek/$subject/',
  path: '/subjek/$subject/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjekSubjectYearRoute = SubjekSubjectYearRouteImport.update({
  id: '/subjek/$subject/$year',
  path: '/subjek/$subject/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const KuizSubjectYearTopicRoute = KuizSubjectYearTopicRouteImport.update({
  id: '/kuiz/$subject/$year/$topic',
  path: '/kuiz/$subject/$year/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profil': typeof ProfilRoute
  '/subjek/': typeof SubjekIndexRoute
  '/subjek/$subject/$year': typeof SubjekSubjectYearRoute
  '/subjek/$subject/': typeof SubjekSubjectIndexRoute
  '/kuiz/$subject/$year/$topic': typeof KuizSubjectYearTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profil': typeof ProfilRoute
  '/subjek': typeof SubjekIndexRoute
  '/subjek/$subject/$year': typeof SubjekSubjectYearRoute
  '/subjek/$subject': typeof SubjekSubjectIndexRoute
  '/kuiz/$subject/$year/$topic': typeof KuizSubjectYearTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profil': typeof ProfilRoute
  '/subjek/': typeof SubjekIndexRoute
  '/subjek/$subject/$year': typeof SubjekSubjectYearRoute
  '/subjek/$subject/': typeof SubjekSubjectIndexRoute
  '/kuiz/$subject/$year/$topic': typeof KuizSubjectYearTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profil'
    | '/subjek/'
    | '/subjek/$subject/$year'
    | '/subjek/$subject/'
    | '/kuiz/$subject/$year/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profil'
    | '/subjek'
    | '/subjek/$subject/$year'
    | '/subjek/$subject'
    | '/kuiz/$subject/$year/$topic'
  id:
    | '__root__'
    | '/'
    | '/profil'
    | '/subjek/'
    | '/subjek/$subject/$year'
    | '/subjek/$subject/'
    | '/kuiz/$subject/$year/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfilRoute: typeof ProfilRoute
  SubjekIndexRoute: typeof SubjekIndexRoute
  SubjekSubjectYearRoute: typeof SubjekSubjectYearRoute
  SubjekSubjectIndexRoute: typeof SubjekSubjectIndexRoute
  KuizSubjectYearTopicRoute: typeof KuizSubjectYearTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjek/': {
      id: '/subjek/'
      path: '/subjek'
      fullPath: '/subjek/'
      preLoaderRoute: typeof SubjekIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjek/$subject/': {
      id: '/subjek/$subject/'
      path: '/subjek/$subject'
      fullPath: '/subjek/$subject/'
      preLoaderRoute: typeof SubjekSubjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjek/$subject/$year': {
      id: '/subjek/$subject/$year'
      path: '/subjek/$subject/$year'
      fullPath: '/subjek/$subject/$year'
      preLoaderRoute: typeof SubjekSubjectYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuiz/$subject/$year/$topic': {
      id: '/kuiz/$subject/$year/$topic'
      path: '/kuiz/$subject/$year/$topic'
      fullPath: '/kuiz/$subject/$year/$topic'
      preLoaderRoute: typeof KuizSubjectYearTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfilRoute: ProfilRoute,
  SubjekIndexRoute: SubjekIndexRoute,
  SubjekSubjectYearRoute: SubjekSubjectYearRoute,
  SubjekSubjectIndexRoute: SubjekSubjectIndexRoute,
  KuizSubjectYearTopicRoute: KuizSubjectYearTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
