/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjekIndexRouteImport } from './routes/subjek.index'
import { Route as SubjekSubjectRouteImport } from './routes/subjek.$subject'
import { Route as SubjekSubjectYearRouteImport } from './routes/subjek.$subject.$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjekIndexRoute = SubjekIndexRouteImport.update({
  id: '/subjek/',
  path: '/subjek/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjekSubjectRoute = SubjekSubjectRouteImport.update({
  id: '/subjek/$subject',
  path: '/subjek/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjekSubjectYearRoute = SubjekSubjectYearRouteImport.update({
  id: '/$year',
  path: '/$year',
  getParentRoute: () => SubjekSubjectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subjek/$subject': typeof SubjekSubjectRouteWithChildren
  '/subjek/': typeof SubjekIndexRoute
  '/subjek/$subject/$year': typeof SubjekSubjectYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subjek/$subject': typeof SubjekSubjectRouteWithChildren
  '/subjek': typeof SubjekIndexRoute
  '/subjek/$subject/$year': typeof SubjekSubjectYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/subjek/$subject': typeof SubjekSubjectRouteWithChildren
  '/subjek/': typeof SubjekIndexRoute
  '/subjek/$subject/$year': typeof SubjekSubjectYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/subjek/$subject' | '/subjek/' | '/subjek/$subject/$year'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/subjek/$subject' | '/subjek' | '/subjek/$subject/$year'
  id:
    | '__root__'
    | '/'
    | '/subjek/$subject'
    | '/subjek/'
    | '/subjek/$subject/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubjekSubjectRoute: typeof SubjekSubjectRouteWithChildren
  SubjekIndexRoute: typeof SubjekIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjek/': {
      id: '/subjek/'
      path: '/subjek'
      fullPath: '/subjek/'
      preLoaderRoute: typeof SubjekIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjek/$subject': {
      id: '/subjek/$subject'
      path: '/subjek/$subject'
      fullPath: '/subjek/$subject'
      preLoaderRoute: typeof SubjekSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjek/$subject/$year': {
      id: '/subjek/$subject/$year'
      path: '/$year'
      fullPath: '/subjek/$subject/$year'
      preLoaderRoute: typeof SubjekSubjectYearRouteImport
      parentRoute: typeof SubjekSubjectRoute
    }
  }
}

interface SubjekSubjectRouteChildren {
  SubjekSubjectYearRoute: typeof SubjekSubjectYearRoute
}

const SubjekSubjectRouteChildren: SubjekSubjectRouteChildren = {
  SubjekSubjectYearRoute: SubjekSubjectYearRoute,
}

const SubjekSubjectRouteWithChildren = SubjekSubjectRoute._addFileChildren(
  SubjekSubjectRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubjekSubjectRoute: SubjekSubjectRouteWithChildren,
  SubjekIndexRoute: SubjekIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
